#!/bin/bash
set -x
dest=$1
selfdir=$(dirname $0)
BGIT=$($selfdir/bgit)
gitdir=$BGIT

git clone $gitdir $dest
cd $dest
mkdir packages/
git config core.worktree ../../
mv .git packages/gitdb
./bbin/resetroot
./bbin/bgit update-index --assume-unchanged ./config/gitdir

echo packages/gitdb >>packages/gitdb/info/exclude
./bbin/bgit repack
./bbin/bgit status