#!/bin/bash
set -x

if [ x$BGIT_BASEDIR != x ] ;then
    if [ -f $BGIT_BASEDIR/bbin/initbashrc ];then
        exit 0
    fi
fi



   selfdir=$(cd 1>/dev/null $(dirname $0);pwd)
   $selfdir/setupbashrc
