#!/bin/bash
set -x
selfdir=$(dirname $0)
cd $selfdir/../
mkdir packages/
git config core.worktree ../../
mv .git packages/gitdb
./bbin/bgit update-index --assume-unchanged ./README ./SETUP
cat ./README >packages/gitdb/description
rm ./README  ./SETUP


echo packages/gitdb >>packages/gitdb/info/exclude
echo .DS_Store >>packages/gitdb/info/exclude

./bbin/bgit repack
./bbin/bgit status
./bbin/initbashrc

