#!/bin/bash
if [ $0 == "-bash" -o $0 == "bash" ];
then
. $BGIT_BASEDIR/lib/bin/import.bash
export PATH=$PATH:/opt/local/bin/:$BGIT_BASEDIR/bin;

return 0
fi

echo "\$0:$0"
set -x


selfdir=$(cd 1>/dev/null $(dirname $0);pwd)

filename=$(basename $0)
basedir=$(cd 1>/dev/null $(dirname $0)/../;pwd)


if  [ ! -f ~/.bash_profile ] ; then
    echo -e "\n\n">~/.bash_profile
    chmod u+x ~/.bash_profile
else if  test $(cat ~/.bash_profile |wc -l ) == 1 ;then
    echo -e "\n\n">>~/.bash_profile
    fi
fi


if  ! grep %%BGIT_IMPORT_SETUP%% ~/.bash_profile -q ; then



tempfile=$(mktemp /tmp/setupbash.XXX)
awk -v n=2 -v s=". \$BGIT_BASEDIR/bbin/setupbashrc   #%%BGIT_IMPORT_SETUP%%" 'NR == n {print s} {print}' ~/.bash_profile >$tempfile

cat  $tempfile >~/.bash_profile
rm $tempfile


tempfile=$(mktemp /tmp/setupbash.XXX)
awk -v n=2 -v s="export BGIT_BASEDIR=$basedir   #%%BGIT_IMPORTDIR_SETUP%%" 'NR == n {print s} {print}' ~/.bash_profile >$tempfile

cat  $tempfile >~/.bash_profile
rm $tempfile




else

tempfile=$(mktemp /tmp/setupbash.XXX)

linenumber=$(grep -n %%BGIT_IMPORTDIR_SETUP%% ~/.bash_profile|sed s/^\\\([0-9]\\\)*.*/\\1/)

cat ~/.bash_profile | sed $linenumber's'!.*!"export BGIT_BASEDIR=$basedir   #%%BGIT_IMPORTDIR_SETUP%%"!  >$tempfile
cat  $tempfile >~/.bash_profile
rm $tempfile



tempfile=$(mktemp /tmp/setupbash.XXX)

linenumber=$(grep -n %%BGIT_IMPORT_SETUP%% ~/.bash_profile|sed s/^\\\([0-9]\\\)*.*/\\1/)

cat ~/.bash_profile | sed $linenumber's'!.*!". \$BGIT_BASEDIR/bbin/setupbashrc   #%%BGIT_IMPORT_SETUP%%"!  >$tempfile
cat  $tempfile >~/.bash_profile
rm $tempfile





fi






